DROP TABLE IF EXISTS thermostat;

CREATE TABLE thermostat (
  time_requested timestamp with time zone primary key,
  time_inserted timestamp with time zone,
  last_connection timestamp with time zone,
  structure_id text,
  device_id text,
  name text,
  name_long text,
  label text,
  where_id text,
  where_name text,
  locale text,
  temperature_scale text,
  is_online boolean,
  hvac_state text,
  hvac_mode text,
  previous_hvac_mode text,
  is_using_emergency_heat boolean,
  has_fan boolean,
  has_leaf boolean,
  can_cool boolean,
  can_heat boolean,
  is_locked boolean,
  sunlight_correction_enabled boolean,
  sunlight_correction_active boolean,
  fan_timer_active boolean,
  fan_timer_timeout timestamp with time zone,
  fan_timer_duration float,
  humidity float,
  ambient_temperature_f float,
  ambient_temperature_c float,
  target_temperature_f float,
  target_temperature_c float,
  target_temperature_low_f float,
  target_temperature_low_c float,
  target_temperature_high_f float,
  target_temperature_high_c float,
  away_temperature_low_f float,
  away_temperature_low_c float,
  away_temperature_high_f float,
  away_temperature_high_c float,
  eco_temperature_low_f float,
  eco_temperature_low_c float,
  eco_temperature_high_f float,
  eco_temperature_high_c float,
  locked_temp_min_f float,
  locked_temp_min_c float,
  locked_temp_max_f float,
  locked_temp_max_c float,
  software_version text
)